#!/bin/bash

# =============================================================================
# Module 05: Cài đặt Tools (05_install_tools.sh)
# Mục tiêu: Cài đặt Certbot, phpMyAdmin và các công cụ thiết yếu khác
# =============================================================================

set -e

# Import cấu hình
source "$(dirname "$(dirname "$(dirname "${BASH_SOURCE[0]}")")")/config.sh"

log_info "=== BƯỚC 6: CÀI ĐẶT TOOLS ==="

# Cài đặt Certbot
log_info "Cài đặt Certbot..."
apt install -y certbot python3-certbot-nginx

# Tạo script tự động gia hạn SSL
cat > /root/ssl_renewal.sh << 'EOF'
#!/bin/bash

# Script tự động gia hạn SSL certificates
LOG_FILE="/var/log/ssl_renewal.log"

echo "$(date): Bắt đầu kiểm tra gia hạn SSL..." >> "$LOG_FILE"

# Gia hạn certificates
certbot renew --quiet --nginx >> "$LOG_FILE" 2>&1

# Reload Nginx
systemctl reload nginx

echo "$(date): Hoàn tất kiểm tra gia hạn SSL." >> "$LOG_FILE"
EOF

chmod +x /root/ssl_renewal.sh

# Thêm cron job tự động gia hạn SSL (hàng ngày lúc 4:00 AM)
(crontab -l 2>/dev/null; echo "0 4 * * * /root/ssl_renewal.sh") | crontab -

log_success "Certbot đã được cài đặt và cấu hình tự động gia hạn!"

# Cài đặt phpMyAdmin
log_info "Cài đặt phpMyAdmin..."

# Download phpMyAdmin
PMA_VERSION="5.2.1"
PMA_URL="https://files.phpmyadmin.net/phpMyAdmin/$PMA_VERSION/phpMyAdmin-$PMA_VERSION-all-languages.tar.gz"

cd /tmp
wget -q "$PMA_URL"
tar -xzf "phpMyAdmin-$PMA_VERSION-all-languages.tar.gz"

# Di chuyển phpMyAdmin đến thư mục web
mv "phpMyAdmin-$PMA_VERSION-all-languages" /var/www/html/phpmyadmin
rm "phpMyAdmin-$PMA_VERSION-all-languages.tar.gz"

# Tạo thư mục tmp cho phpMyAdmin
mkdir -p /var/www/html/phpmyadmin/tmp
chown -R www-data:www-data /var/www/html/phpmyadmin
chmod 755 /var/www/html/phpmyadmin/tmp

# Lấy thông tin database phpMyAdmin từ credentials
PMA_DB_PASSWORD=$(grep "PMA_DB_PASSWORD" "$CREDENTIALS_FILE" | cut -d'=' -f2)

# Tạo cấu hình phpMyAdmin
log_info "Cấu hình phpMyAdmin..."

# Tạo blowfish secret
PMA_BLOWFISH_SECRET=$(generate_blowfish_secret)

cat > /var/www/html/phpmyadmin/config.inc.php << EOF
<?php
/**
 * phpMyAdmin configuration
 * Generated by VPS Management Script
 */

// Basic settings
\$cfg['blowfish_secret'] = '$PMA_BLOWFISH_SECRET';
\$cfg['DefaultLang'] = 'vi';
\$cfg['ServerDefault'] = 1;
\$cfg['UploadDir'] = '$PMA_UPLOAD_DIR';
\$cfg['SaveDir'] = '$PMA_TEMP_DIR';

// Servers configuration
\$i = 0;

// First server (localhost)
\$i++;
\$cfg['Servers'][\$i]['auth_type'] = 'cookie';
\$cfg['Servers'][\$i]['host'] = 'localhost';
\$cfg['Servers'][\$i]['compress'] = false;
\$cfg['Servers'][\$i]['AllowNoPassword'] = false;

// Control database settings
\$cfg['Servers'][\$i]['controlhost'] = 'localhost';
\$cfg['Servers'][\$i]['controlport'] = '';
\$cfg['Servers'][\$i]['controluser'] = 'phpmyadmin';
\$cfg['Servers'][\$i]['controlpass'] = '$PMA_DB_PASSWORD';
\$cfg['Servers'][\$i]['pmadb'] = 'phpmyadmin';
\$cfg['Servers'][\$i]['bookmarktable'] = 'pma__bookmark';
\$cfg['Servers'][\$i]['relation'] = 'pma__relation';
\$cfg['Servers'][\$i]['table_info'] = 'pma__table_info';
\$cfg['Servers'][\$i]['table_coords'] = 'pma__table_coords';
\$cfg['Servers'][\$i]['pdf_pages'] = 'pma__pdf_pages';
\$cfg['Servers'][\$i]['column_info'] = 'pma__column_info';
\$cfg['Servers'][\$i]['history'] = 'pma__history';
\$cfg['Servers'][\$i]['table_uiprefs'] = 'pma__table_uiprefs';
\$cfg['Servers'][\$i]['tracking'] = 'pma__tracking';
\$cfg['Servers'][\$i]['userconfig'] = 'pma__userconfig';
\$cfg['Servers'][\$i]['recent'] = 'pma__recent';
\$cfg['Servers'][\$i]['favorite'] = 'pma__favorite';
\$cfg['Servers'][\$i]['users'] = 'pma__users';
\$cfg['Servers'][\$i]['usergroups'] = 'pma__usergroups';
\$cfg['Servers'][\$i]['navigationhiding'] = 'pma__navigationhiding';
\$cfg['Servers'][\$i]['savedsearches'] = 'pma__savedsearches';
\$cfg['Servers'][\$i]['central_columns'] = 'pma__central_columns';
\$cfg['Servers'][\$i]['designer_settings'] = 'pma__designer_settings';
\$cfg['Servers'][\$i]['export_templates'] = 'pma__export_templates';

// Security settings
\$cfg['LoginCookieValidity'] = 3600;
\$cfg['LoginCookieStore'] = 3600;
\$cfg['LoginCookieDeleteAll'] = true;
\$cfg['UseDbSearch'] = true;
\$cfg['IgnoreMultiSubmitError'] = true;

// Interface settings
\$cfg['ThemeDefault'] = 'pmahomme';
\$cfg['DefaultTabServer'] = 'welcome';
\$cfg['DefaultTabDatabase'] = 'structure';
\$cfg['DefaultTabTable'] = 'sql';
\$cfg['RowActionLinks'] = 'left';
\$cfg['ShowStats'] = true;
\$cfg['ShowServerInfo'] = false;
\$cfg['ShowPhpInfo'] = false;
\$cfg['ShowChgPassword'] = true;
\$cfg['ShowCreateDb'] = true;
\$cfg['SuggestDBName'] = true;

// Export/Import settings
\$cfg['Export']['lock_tables'] = true;
\$cfg['Export']['charset'] = 'utf-8';
\$cfg['Import']['charset'] = 'utf-8';

// SQL query settings
\$cfg['MaxRows'] = 50;
\$cfg['Order'] = 'SMART';
\$cfg['BrowsePointerEnable'] = true;
\$cfg['BrowseMarkerEnable'] = true;

// Error reporting
\$cfg['Error_Handler']['display'] = false;
\$cfg['Error_Handler']['gather'] = false;
?>
EOF

# Import phpMyAdmin database structure
log_info "Import cấu trúc database phpMyAdmin..."
mysql phpmyadmin < /var/www/html/phpmyadmin/sql/create_tables.sql

# Tạo cấu hình Nginx cho phpMyAdmin
log_info "Cấu hình Nginx cho phpMyAdmin..."

cat > /etc/nginx/sites-available/phpmyadmin << 'EOF'
# phpMyAdmin Nginx configuration
location /phpmyadmin {
    alias /var/www/html/phpmyadmin;
    index index.php index.html index.htm;
    
    # Security headers
    add_header X-Frame-Options "SAMEORIGIN" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header X-Content-Type-Options "nosniff" always;
    
    # Rate limiting for phpMyAdmin
    limit_req zone=login burst=5 nodelay;
    
    # Deny access to sensitive files
    location ~ ^/phpmyadmin/(libraries|setup|templates)/ {
        deny all;
    }
    
    location ~ ^/phpmyadmin/(.+\.php)$ {
        alias /var/www/html/phpmyadmin/$1;
        
        # Security checks
        location ~ ^/phpmyadmin/(libraries|setup)/.*\.php$ {
            deny all;
        }
        
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.3-fpm.sock;
        fastcgi_param SCRIPT_FILENAME $request_filename;
        include fastcgi_params;
    }
    
    location ~* ^/phpmyadmin/(.+\.(jpg|jpeg|gif|css|png|js|ico|html|xml|txt))$ {
        alias /var/www/html/phpmyadmin/$1;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
EOF

# Include cấu hình phpMyAdmin vào site mặc định
sed -i '/location ~ \.php\$ {/i\    include /etc/nginx/sites-available/phpmyadmin;\n' /etc/nginx/sites-available/default

# Test và reload Nginx
nginx -t && systemctl reload nginx

log_success "phpMyAdmin đã được cài đặt và cấu hình!"

# Cài đặt các công cụ bổ sung
log_info "Cài đặt các công cụ bổ sung..."

# Composer
log_info "Cài đặt Composer..."
cd /tmp
curl -sS https://getcomposer.org/installer | php
mv composer.phar /usr/local/bin/composer
chmod +x /usr/local/bin/composer

# WP-CLI
log_info "Cài đặt WP-CLI..."
curl -O https://raw.githubusercontent.com/wp-cli/wp-cli/v2.8.1/wp-cli.phar
chmod +x wp-cli.phar
mv wp-cli.phar /usr/local/bin/wp

# Node.js và npm
log_info "Cài đặt Node.js..."
curl -fsSL https://deb.nodesource.com/setup_lts.x | bash -
apt install -y nodejs

log_success "Đã cài đặt Node.js $(node --version) và npm $(npm --version)"

# Git configuration
log_info "Cấu hình Git..."
git config --system init.defaultBranch main
git config --system pull.rebase false

# Tạo script SSL helper
log_info "Tạo script SSL helper..."

cat > /usr/local/bin/ssl-cert << 'EOF'
#!/bin/bash

# SSL Certificate Helper Script
# Usage: ssl-cert <domain> [email]

if [[ $# -lt 1 ]]; then
    echo "Sử dụng: $0 <domain> [email]"
    echo "Ví dụ: $0 example.com admin@example.com"
    exit 1
fi

DOMAIN="$1"
EMAIL="${2:-admin@$DOMAIN}"

echo "🔒 Tạo SSL certificate cho domain: $DOMAIN"
echo "📧 Email: $EMAIL"

# Kiểm tra domain có trỏ về server này không
SERVER_IP=$(curl -s ifconfig.me)
DOMAIN_IP=$(dig +short "$DOMAIN" A | tail -n1)

if [[ "$SERVER_IP" != "$DOMAIN_IP" ]]; then
    echo "⚠️  Cảnh báo: Domain $DOMAIN không trỏ về server này!"
    echo "   Server IP: $SERVER_IP"
    echo "   Domain IP: $DOMAIN_IP"
    echo -n "Bạn có muốn tiếp tục? (y/N): "
    read -r confirm
    if [[ ! "$confirm" =~ ^[Yy]$ ]]; then
        echo "Hủy bỏ."
        exit 0
    fi
fi

# Tạo SSL certificate
certbot --nginx -d "$DOMAIN" --email "$EMAIL" --agree-tos --non-interactive

if [[ $? -eq 0 ]]; then
    echo "✅ SSL certificate đã được tạo thành công!"
    echo "🌐 https://$DOMAIN"
else
    echo "❌ Lỗi tạo SSL certificate!"
    exit 1
fi
EOF

chmod +x /usr/local/bin/ssl-cert

# Tạo script quản lý site
cat > /usr/local/bin/site-manager << 'EOF'
#!/bin/bash

# Simple Site Manager
# Usage: site-manager <action> [options]

show_help() {
    cat << 'HELP'
Site Manager - Quản lý website đơn giản

Sử dụng:
    site-manager list                    - Liệt kê các site
    site-manager create <domain> [php]   - Tạo site mới
    site-manager delete <domain>         - Xóa site
    site-manager enable <domain>         - Kích hoạt site
    site-manager disable <domain>        - Vô hiệu hóa site

Ví dụ:
    site-manager create example.com 8.3
    site-manager delete example.com
HELP
}

list_sites() {
    echo "=== Danh sách các site ==="
    echo "Enabled sites:"
    ls -1 /etc/nginx/sites-enabled/ 2>/dev/null || echo "  Không có site nào được kích hoạt"
    echo ""
    echo "Available sites:"
    ls -1 /etc/nginx/sites-available/ 2>/dev/null || echo "  Không có site nào"
}

if [[ $# -eq 0 ]]; then
    show_help
    exit 0
fi

case "$1" in
    list|ls)
        list_sites
        ;;
    help|-h|--help)
        show_help
        ;;
    *)
        echo "Chức năng $1 đang được phát triển..."
        echo "Sử dụng: site-manager help để xem trợ giúp"
        ;;
esac
EOF

chmod +x /usr/local/bin/site-manager

# Tạo script hệ thống info
cat > /usr/local/bin/server-info << 'EOF'
#!/bin/bash

# Server Information Script
echo "================================================================"
echo "                    SERVER INFORMATION"
echo "================================================================"

echo "🖥️  System Info:"
echo "   OS: $(lsb_release -d | cut -f2)"
echo "   Kernel: $(uname -r)"
echo "   Uptime: $(uptime -p)"
echo "   Load: $(uptime | awk -F'load average:' '{print $2}')"

echo ""
echo "💾 Memory & Storage:"
echo "   RAM: $(free -h | awk '/^Mem:/{printf "%s / %s (%.1f%%)\n", $3, $2, $3/$2*100}')"
echo "   Disk: $(df -h / | awk 'NR==2{printf "%s / %s (%s used)\n", $3, $2, $5}')"

echo ""
echo "🌐 Network:"
echo "   Public IP: $(curl -s ifconfig.me)"
echo "   Private IP: $(hostname -I | awk '{print $1}')"

echo ""
echo "🔧 Services Status:"
services=("nginx" "mariadb" "redis-server" "php7.4-fpm" "php8.3-fpm")
for service in "${services[@]}"; do
    if systemctl is-active --quiet "$service"; then
        status="🟢 Running"
    else
        status="🔴 Stopped"
    fi
    printf "   %-15s: %s\n" "$service" "$status"
done

echo ""
echo "📊 Quick Stats:"
echo "   Active connections: $(ss -t | wc -l)"
echo "   Running processes: $(ps aux | wc -l)"
echo "   Open files: $(lsof | wc -l)"

echo "================================================================"
EOF

chmod +x /usr/local/bin/server-info

# Set quyền cho các file đã tạo
chown www-data:www-data /var/www/html/phpmyadmin/config.inc.php
chmod 644 /var/www/html/phpmyadmin/config.inc.php

# Ghi thông tin vào credentials file
cat >> "$CREDENTIALS_FILE" << EOF

# Tools Configuration
CERTBOT_PATH=/usr/bin/certbot
SSL_RENEWAL_SCRIPT=/root/ssl_renewal.sh

# phpMyAdmin
PMA_VERSION=$PMA_VERSION
PMA_PATH=/var/www/html/phpmyadmin
PMA_URL=http://$(hostname -I | awk '{print $1}')/phpmyadmin
PMA_BLOWFISH_SECRET=$PMA_BLOWFISH_SECRET

# Development Tools
COMPOSER_PATH=/usr/local/bin/composer
WP_CLI_PATH=/usr/local/bin/wp
NODE_VERSION=$(node --version)
NPM_VERSION=$(npm --version)

# Helper Scripts
SSL_CERT_HELPER=/usr/local/bin/ssl-cert
SITE_MANAGER=/usr/local/bin/site-manager
SERVER_INFO=/usr/local/bin/server-info

EOF

log_success "Module Tools hoàn tất!"

echo ""
echo "=== Thông tin Tools đã cài đặt ==="
echo "🔒 Certbot: $(certbot --version | head -1)"
echo "🗄️  phpMyAdmin: v$PMA_VERSION"
echo "   URL: http://$(hostname -I | awk '{print $1}')/phpmyadmin"
echo "🎼 Composer: $(composer --version | head -1)"
echo "📝 WP-CLI: $(wp --version)"
echo "🟢 Node.js: $(node --version)"
echo "📦 npm: $(npm --version)"

echo ""
echo "=== Các công cụ helper ==="
echo "• ssl-cert <domain>     - Tạo SSL certificate"
echo "• site-manager         - Quản lý website"
echo "• server-info          - Thông tin server"
echo "• redis-monitor        - Giám sát Redis"
echo "• php-status           - Trạng thái PHP"
